   
import Sidebar from "./Sidebar";

// Metadata for the page
export const metadata = {
    title: "Online Exam Services",
    description: "Generated by create next app",
};



export default function ServicesLayout({ children }) {
  
    return (
        <div className="flex">
            {/* Sidebar */}
            <aside className="w-[28%] p-4  h-screen bg-blue-500 text-white">
                <Sidebar />
            </aside>

            {/* Main Content */}
            <main className=" flex-1 h-screen overflow-y-auto scrollbar-hidden bg-gray-200 p-4">
                {children}
            </main>
        </div>
    );
}
